name: CI

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - uses: actions/checkout@v4
      - name: Test
        run: go test -race ./...

  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v2
        with:
          languages: go
      - uses: github/codeql-action/analyze@v2

  release:
    name: Release
    needs: [test, analyze]
    if: "contains(github.ref, 'tags/v')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install upx
        run: sudo apt install upx -y
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
